  
---

- name: Install Apache package
  package:
    name: httpd
    state: installed

- name: Enable service httpd
  systemd:
    name: httpd
    enabled: yes

- name: firewalld permits http service
  firewalld:
    service: http
    permanent: true
    state: enabled
    immediate: yes

- name: firewalld permits http service
  firewalld:
    service: https
    permanent: true
    state: enabled
    immediate: yes

- name: Ensure httpd service is restarted
  service:
    name: httpd
    state: restarted
