---
- name: Install webservers packages
  yum:
    name: httpd
    state: latest

- name: copy index.html for OS-6
  copy:
    src: /ansible/role/web6/templates/index.html
    dest: /var/www/html/
    owner: root
    group: root
    mode: '0666'

