---
- name: Yum update all
  yum:
    name: '*'
    state: latest

- name: Install haproxy
  yum: 
    name: haproxy
    state: latest

- name: Copy haproxy.cfg
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg

- name: Copy logs config file
  template:
    src: haproxy.conf.j2
    dest: /etc/rsyslog.d/haproxy.conf

- name: Copy new rsyslog file
  template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.conf
