---

- name: install epel
  yum:
    name: epel-release
    state: present
    
- name: install squirrelmail
  yum:
    name: squirrelmail
    state: present

- name: Install Squirrelmail configuration
  template:
    src: squirrelmail.config.php.j2
    dest: /usr/share/squirrelmail/config/config.php

- name: install apache
  yum: 
    name: httpd
    state: present

- name: configure httpd
  template: 
    src: httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf

- name: start httpd
  service:
    name: httpd
    state: started
    enabled: true
