---
- name: Restart rsyslog
  service:
    name: rsyslog
    state: restarted

- name: Start and enable haproxy
  service:
    name: haproxy
    state: started
    enabled: true

- name: Restart service haproxy
  service:
    name: haproxy
    state: restarted

